### ISSUE TITLE
[QUESTION] Confidence Score

### ISSUE THREAD

**Issue by JayR7** [CAMeL-Lab/camel_tools#100]
Greetings,
I have a quick question, is there a way to get the confidence scores of each document's sentiment?

Thanks!

**Comment by balhafni** [comment]
We do not expose the softmax probability distribution over the predicted labels but you can access them from here: https://github.com/CAMeL-Lab/camel_tools/blob/d2ca29c8771cd7cf0753e6bf65b7bac28b814bc6/camel_tools/sentiment/__init__.py#L164
