### ISSUE TITLE
[QUESTION] How to use camel_diac tool in CLI? 

### ISSUE THREAD

**Issue by yurtmete** [CAMeL-Lab/camel_tools#104]
Hi, 

I would like to use **camel_diac** tool to apply Arabic Text Diacritization. It looks like you have a CLI command for this: https://camel-tools.readthedocs.io/en/latest/cli/camel_diac.html

However, I cannot make it run. Could you specify how I am supposed to pass the undiacritized Arabic text to it? Could you give an example maybe?

Thank you for the great source!

**Comment by aydin33** [comment]
hello, i have the same question. How can i pass the undiacritized text as input?

Thank you

**Comment by slkh** [comment]
Can you provide MWE you have tried? This will help in narrowing down the issue more efficiently.

**Comment by Aml-Hassan-Abd-El-hamid** [comment]
Does anybody know how to use this function, camel_diac? like how am I supposed to pass the input

**Comment by slkh** [comment]
I'm assuming you are using it through the CLI. If that is the case you pass the input as a regular text file.
