### ISSUE TITLE
Adding more details about the tools in the README

### ISSUE THREAD

**Issue by AMR-KELEG** [CAMeL-Lab/camel_tools#11]
Dear CAMel tools contributors,

I am enthusiast about the tools but I can't find any information about the features that are currently available in the README.md file.
Can you please update it so that it's easier to navigate the repo?

Thanks,
Amr

**Comment by balhafni** [comment]
Hi @AMR-KELEG,

The tools that are available in the current release can be found in the [docs](https://camel-tools.readthedocs.io/en/latest/?badge=latest).
