### ISSUE TITLE
Issue of conflicting dependencies.

### ISSUE THREAD

**Issue by EttananiaHamza** [CAMeL-Lab/camel_tools#111]
Hello there;

I have an issue installing camel-tools; while using the command "pip install camel-tools", there is an error message that is given, which is as follows:

ERROR: Cannot install camel-tools==1.0.1, camel-tools==1.1.0 and camel-tools==1.2.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    camel-tools 1.2.0 depends on torch>=1.3
    camel-tools 1.1.0 depends on torch>=1.3
    camel-tools 1.0.1 depends on torch>=1.3

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

I am on Windows 10, and I am using Python 3.11.2. 

<img width="960" alt="Screenshot 2023-03-02 140833" src="https://user-images.githubusercontent.com/126774993/222411913-23cbcc10-8e8e-4d28-97ae-5656a3e55f53.png">

**Comment by owo** [comment]
This is now fixed with the latest release of camel-tools.
