### ISSUE TITLE
[BUG] Arclean not handling Arabic Farsi yeh correctly

### ISSUE THREAD

**Issue by muhammed-abuodeh** [CAMeL-Lab/camel_tools#117]
**Describe the bug**
The Arabic Farsi yeh (unicode 06CC) is converted to the Arabic alef maksura (0649). The problem is that the initial and medial forms of 06CC will appear with dots (i.e. تجرید and یحقق) but without dots in the end and alone (i.e. ألقی and ی).

**To Reproduce**
Run the above words with arclean and check the unicode output:

```
from camel_tools.utils.charmap import CharMapper

arclean = CharMapper.builtin_mapper("arclean")

arclean('تجرید') # output: تجرىد
arclean('یحقق') # output: ىحقق

arclean('ألقی') # output: ألقى
arclean('ی') # output: ى

```

**Expected behavior**
For the initial and medial cases it may be better to convert to the Arabic yeh (064A), and Arabic alef maksura (0649) for the end and alone.

**Comment by owo** [comment]
For now this can't be done using CharMapper as it doesn't look at context.
We would have to write a separate cleaning function to handle this.
