### ISSUE TITLE
How lemmatization works

### ISSUE THREAD

**Issue by alvelvis** [CAMeL-Lab/camel_tools#12]
Hi, people from CAMeL,
I don't understand how lemmatization works when I use calima_star module from Camel Tools (which I installed through pip).
The "lex" feature has numbers before the word itself (1_, 2_ etc.), and some have numbers after the word (_0), or even -1. What are those marks supposed to be, is there any reading you would recommend me?
Plus, is it safe to just strip those marks?
Thanks in advance

**Comment by slkh** [comment]
Hi Elvis ––

The lemma markers are actually of two types:

(1) `_0` indicates that the lemma is not in the lexicon -- it is the result of a default process or a backoff process.

(2) `_[123456789]+` indicates a different sense of the base lemma. These are inherited from the BAMA/SAMA lexicons and are not consistent or complete. We keep them for historical reasons.

(Can you also give us an example of the `-1` case you mentioned?)

In addition to the above, some lemmas have a designation `-[uai]+` that specifies some morphology details. This designation appears before the digit marker: e.g. (`lex:كَتَب-u_1` ). We have found this to be unhelpful in general and in fact we do not use any of these markers in our models.  So, the recommendation is to strip them.

This is the regex we recommenced to use to strip the markers from the lemmas:
```
stripped_lemma = re.split(r'-|_', lemma)[0]
```

**Comment by alvelvis** [comment]
Hi Salam,
Thank you very much for the answer.
Where I said `-1`, I meant `-ui_1`, so you already answered it.
Thanks for the regex, too. Closing this issue :)
