### ISSUE TITLE
[QUESTION] About errors of spelling

### ISSUE THREAD

**Issue by manel-hikk** [CAMeL-Lab/camel_tools#135]
Hi
I'm cleaning an arabic dataset 
My arabic text has some errors and I saw in the docs the module **camel_tools.morphology.errors.MorphologyError**
So I was thinking may be this module is for errors like the repeating characters.
but unfortenatly the docs don't have enough [examples](https://github.com/CAMeL-Lab/camel_tools/blob/master/docs/source/api/morphology/errors.rst).
so is there any module in camel tools that check grammar or orthographic errors and correct it?

**Comment by owo** [comment]
We unfortunately don't have a spelling and grammar correction components at the moment.
`MorphologyError` is just a base class for all exceptions raised by morphology components for invalid arguments (e.g. passing an invalid flag to [MorphologyDB](https://camel-tools.readthedocs.io/en/latest/api/morphology/database.html#camel_tools.morphology.database.MorphologyDB)) and not for erroneous text like you mention.
