### ISSUE TITLE
[BUG] Problem with installing camel-tools library via PIP

### ISSUE THREAD

**Issue by israaexol** [CAMeL-Lab/camel_tools#144]
Hello,

Since yesterday afternoon, there has been an issue with installing the camel-tools library via PIP (kindly see attached screenshot). 
Thinking that it might be an issue on my side, I tried on different environments but it seems like the issue is from the library itself.

Is there any update regarding the fix of this issue? I hope it'll be resolved asap 

Thank you! Looking forward to hearing back from you
![camel_error](https://github.com/CAMeL-Lab/camel_tools/assets/47036943/b5e6e127-4f4f-480c-9af0-3d225cb0df21)

**Comment by owo** [comment]
Can you try running `pip install --upgrade --force-reinstall camel-tools`?
There was an issue with one of the dependencies and should now be fixed.
