### ISSUE TITLE
Finetuning instructions

### ISSUE THREAD

**Issue by omarabb315** [CAMeL-Lab/camel_tools#147]
Is there any way to finetune the lemmatization tool?

**Comment by owo** [comment]
Are you referring to the [BERTUnfactoredDisambiguator](https://camel-tools.readthedocs.io/en/latest/api/disambig/bert.html#camel_tools.disambig.bert.BERTUnfactoredDisambiguator)?

Unfortunately there's no way to do this within CAMeL Tools at the moment (although that may change in the future).

Furthermore, it's important to note that our model isn't fine-tuned on lemmas but rather we produce lemmas as a byproduct of predicting other features.

You can read more in [this paper](https://arxiv.org/abs/2110.06852). We also provide the original CAMeLBERT models ([GitHub](https://github.com/CAMeL-Lab/CAMeLBERT), [Hugging Face](https://huggingface.co/CAMeL-Lab)) which you can use.
