### ISSUE TITLE
camel_tools.ner not found

### ISSUE THREAD

**Issue by akkiverma22** [CAMeL-Lab/camel_tools#25]
Hi All, 

I am trying to use camel_tools for ner and i git the error camel_tools.ner not found.

Thanks,
Akash

**Comment by owo** [comment]
Hi @akkiverma22 ,

Can you tell me how you installed camel_tools?
Did you install the pip package or from source?
The NER component is not available on pip at the moment.

**Comment by akkiverma22** [comment]
Q) Can you tell me how you installed camel_tools?
pip install --upgrade --force-reinstall camel-tools

Q) Did you install the pip package or from source?
PIP

Q) The NER component is not available on pip at the moment.
Can you please provide the way so that we can use the NER component.

**Comment by owo** [comment]
After [installing camel_tools from source](https://github.com/CAMeL-Lab/camel_tools#installation) (including the data files), please try the [usage example](https://camel-tools.readthedocs.io/en/latest/api/ner.html#examples) to confirm everything works.

**Comment by owo** [comment]
Hi @akkiverma22,

Is this resolved?

I'm closing this issue since I haven't heard back but I will reopen it if there are any problems still.
