### ISSUE TITLE
Transilteration of Arabic text

### ISSUE THREAD

**Issue by rhiatinabil** [CAMeL-Lab/camel_tools#27]
I could not find help on the Camel Tools help on how to use the transliteration utility.  If you could provide me with Python sample code I will appreciate it.
Thank you
Here is some code I have tried:

from camel_tools.utils import *
s = "وَاخْرٍ الكلمات العربية في حال تركيبها: من الإعراب"
#print(s)
text = Transliterator.transliterate(s,strip_markers=False, ignore_markers=False)
print (text)

**Comment by owo** [comment]
Hi @rhiatinabil ,

If all you want is basic transliteration, you should use a [CharMapper](https://camel-tools.readthedocs.io/en/latest/api/utils/charmap.html#camel_tools.utils.charmap.CharMapper) like so:

```python
from camel_tools.utils.charmap import CharMapper

# We will transliterate Arabic script to Buckwalter encoding
ar2bw = CharMapper.builtin_mapper('ar2bw')
sentence = "وَاخْرٍ الكلمات العربية في حال تركيبها: من الإعراب"
transliterated = ar2bw.map_string(sentence)
print(transliterated)
```

This should output:

```
waAxorK AlklmAt AlErbyp fy HAl trkybhA: mn Al<ErAb
```

The [Transliterator](https://camel-tools.readthedocs.io/en/latest/api/utils/transliterate.html#camel_tools.utils.transliterate.Transliterator) class provides a wrapper around CharMapper to ignore words that have a particular prefix.
This is particularly useful when transliterating from the various Buckwalter encodings into Arabic to prevent transliterating foreign words.
The default prefix is `@@IGNORE@@`.
The Transliterator can be used like so:

```python
from camel_tools.utils.charmap import CharMapper
from camel_tools.utils.transliterate import Transliterator


# We will transliterate from Buckwalter encoding to Arabic script
bw2ar = CharMapper.builtin_mapper('bw2ar')
bw2ar_trans = Transliterator(bw2ar)
sentence = 'waAxorK AlklmAt @@IGNORE@@AlErbyp fy HAl trkybhA: mn Al<ErAb'

# This will keep the markers in the output
transliterated = bw2ar_trans.transliterate(sentence)
print(transliterated)

# This will remove the markers in the output
transliterated_no_mark = bw2ar_trans.transliterate(sentence, True)
print(transliterated_no_mark) 
```

which should output:

```
وَاخْرٍ الكلمات @@IGNORE@@AlErbyp في حال تركيبها: من الإعراب
وَاخْرٍ الكلمات AlErbyp في حال تركيبها: من الإعراب
```

You can find a list of available transliteration schemes [here](https://camel-tools.readthedocs.io/en/latest/api/utils/charmap.html#built-in-mappings) and a conversion table of these schemes [here](https://camel-tools.readthedocs.io/en/latest/reference/encoding_schemes.html#encoding-schemes).

I hope that helps.

**Comment by owo** [comment]
Hi @rhiatinabil ,

Did this work?

I'm closing the issue if there are no further problems.

**Comment by AhmedNabil-99** [comment]
Hi @owo 
I  used your code :
from camel_tools.utils.charmap import CharMapper

# We will transliterate Arabic script to Buckwalter encoding
ar2bw = CharMapper.builtin_mapper('ar2bw')
sentence = "وَاخْرٍ الكلمات العربية في حال تركيبها: من الإعراب"
transliterated = ar2bw.map_string(sentence)
print(transliterated)

But this error appears:
    from camel_tools.utils.charmap import CharMapper
ImportError: No module named camel_tools.utils.charmap

I hope you may help my solving this error

**Comment by owo** [comment]
Hi @AhmedNabil-99 ,

The code runs just fine.
Are you sure you installed camel-tools?
It could be you installed it on a different Python version than you're running example with.
This could happen if you are using multiple virtual environments or if you updated to a different Python version after installing camel-tools.
If you're running on Google Collab, you'll have to reinstall camel-tools evry session you use it.
