### ISSUE TITLE
[QUESTION] camel_tools.ner.NERecognizer.pretrained cannot load AraBERT model provided with camel-tools...

### ISSUE THREAD

**Issue by abosoar** [CAMeL-Lab/camel_tools#34]
**Problem in loading AraBERT model**
when writing the following code:
```python
from camel_tools.ner import NERecognizer
recognizer = NERecognizer.pretrained()
recognizer.predict('دولار')
```
I get the following error
```python
OSError: Can't load config for '/root/.camel_tools/data/ner/arabert'. Make sure that:`
- '/root/.camel_tools/data/ner/arabert' is a correct model identifier listed on 'https://huggingface.co/models'

- or '/root/.camel_tools/data/ner/arabert' is the correct path to a directory containing a config.json file

```
How to solve this problem

**Comment by abosoar** [comment]
solved after installing data using the command
```bash 
camel_data full 
```

**Comment by owo** [comment]
I'm glad the issue is resolved.

Just a note, your code should be something like the following:

```python
from camel_tools.ner import NERecognizer
recognizer = NERecognizer.pretrained()

recognizer.predict([['دولار']])

# or
recognizer.predict_sentence(['دولار'])
```

The input should be a pre-tokenized sentence that has been split by white-space and punctuation.
See [here](https://camel-tools.readthedocs.io/en/latest/api/ner.html#examples) for details on NER and [here](https://camel-tools.readthedocs.io/en/latest/api/tokenizers/word.html#camel_tools.tokenizers.word.simple_word_tokenize) for a utility that does this splitting for you.

**Comment by abosoar** [comment]
> I'm glad the issue is resolved.
> 
> Just a note, your code should be something like the following:
> 
> ```python
> from camel_tools.ner import NERecognizer
> recognizer = NERecognizer.pretrained()
> 
> recognizer.predict([['دولار']])
> 
> # or
> recognizer.predict_sentence(['دولار'])
> ```
> 
> The input should be a pre-tokenized sentence that has been split by white-space and punctuation.
> See [here](https://camel-tools.readthedocs.io/en/latest/api/ner.html#examples) for details on NER and [here](https://camel-tools.readthedocs.io/en/latest/api/tokenizers/word.html#camel_tools.tokenizers.word.simple_word_tokenize) for a utility that does this splitting for you.

Thanks for replying!
I will take that into consideration.
It would be helpful if there is a discussion forum to negotiate various issues.

**Comment by owo** [comment]
I'll be working on setting up GitHub's new Discussions feature soon which is very much like a forum.
Keep an eye out for that :)

**Comment by maimdeep** [comment]
i couldnt install the camel_data full that you've mentioned .. 
any other solutions ?

**Comment by owo** [comment]
Hi @maimdeep 

You're probably using the old way of installing data.
Please make sure you have the latest camel_tools and install data by running `camel_data -i full`.
