### ISSUE TITLE
Optimise NERecognizer's prediction speed

### ISSUE THREAD

**Issue by awadomar34** [CAMeL-Lab/camel_tools#38]
**What feature would you like to improve?**
```NERecognizer()```

**Is your enhancement request related to a problem? Please describe.**
I tested the speed of ```NERecognizer().pretrained()``` at making predictions. It takes 374.11 seconds to predict 549 sentences (on average, each sentence has 10.36 words and 60.87 characters). This is too slow to use for live analytical tools which process social media posts.

**Describe the solution you'd like**
I was wondering if there was a way to speed up this method?
Or if you could help me understand why it takes this long?

**Comment by balhafni** [comment]
Hi @awadomar34,

Which function are you using to get the predictions? Are you using `predict_sentence()` to get the predictions of each sentence at a time? If so, could you try using `predict()` instead? `predict()` takes a list of list of white-space tokenized sentences and we're currently using a batch size of 8 by default. As of now, the NER component has CPU support only and we're looking into adding GPU support as well.

**Comment by balhafni** [comment]
This has been fixed and you can now use the NER component on GPUs.
