### ISSUE TITLE
[QUESTION] Custom pre-trained model

### ISSUE THREAD

**Issue by BodaSadalla98** [CAMeL-Lab/camel_tools#40]
Hey, I would like to ask, if there's a way to use the NER module with custom model trained on different dataset.
right now CAMEL uses  one pre-trained model (`arabert`) that's trained on  `ANERCorp` , to do NER task.

question is, can we train this model (`arabert`) on different dataset and use it,  or can we train a new model and use it ? 

Thx

**Comment by balhafni** [comment]
You should be able to use the NER component with your own fine-tuned model as follows:

```bash
from camel_tools.ner import NERecognizer
ner_model = NERecognizer('/path/to/model')
```

So you can fine-tuned any other BERT model on NER and load it into our NER component. As of now, we do not provide any fine-tuning code to train new models.

**Comment by owo** [comment]
I would just like to add, that on our todo list is having a simplified training interface to our ML models including NER.
This would include performing any preprocesing steps performed before training.
I can't promise a particular time estimate, but please check in every now and then.
