### ISSUE TITLE
Verb Tenses

### ISSUE THREAD

**Issue by Linah-Bakhsh** [CAMeL-Lab/camel_tools#42]
I would like to ask if there are any morphological feature describe the verb tenses? 
e.g: if the verb is: future, past, present.

Thank u :)

**Comment by nizarhabash1** [comment]
Hi Linah,

There is no direct one to one mapping as the tense depends on a mix of
morphological and syntactic conditions.

The feature aspect has two values that can help here: perfective (asp:p) is
الماضي and generally maps to “past” and imperfective (asp:i) is المضارع
which can be associated with “present”, “future”, and even “past”. To
distinguish these three readings Arabic uses the future particle sa
(prc1:sa_fut) for indicating future; the Indicative mood feature (mod:i)
المضارع المرفوع generally means present. The other two moods have varying
mappings to future and past based on other particles in the sentence
syntax: لن يذهبَ has asp:i mod:s (subjunctive منصوب) and here it is future;
and لم يذهبْ has asp:i mod:j (jussive ~ مجزوم) and is past.
The imperfective dependence on extra particles reminds me a bit of
English’s bare infinitive In constructions like (he will go, he *did* go,
he didn’t go, he can go now).

I hope this helps,

Nizar


On Thu, 11 Feb 2021 at 10:51 PM Linah-Bakhsh <notifications@github.com>
wrote:

> I would like to ask if there are any morphological feature describe the
> verb tenses?
> e.g: if the verb is: future, past, present.
>
> Thank u :)
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_CAMeL-2DLab_camel-5Ftools_issues_42&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=fJnOX_UKiq6ZVZFnb0oywg&m=xDTZdvzqobFTCyd-glFfhRJjKGJgFfXlwCjz-j6RtsI&s=Pn6VtZ6ZEn_gcPggr4vVBvapRi7Y2IvVBXATzlUMn7c&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AC2U5YNLVYGZJFRLLJCO3LTS6QRKNANCNFSM4XPLKWJQ&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=fJnOX_UKiq6ZVZFnb0oywg&m=xDTZdvzqobFTCyd-glFfhRJjKGJgFfXlwCjz-j6RtsI&s=N6hqyN9ZN8_VLimvngf8_d5Div_THpS2dN_xKbkrdzM&e=>
> .
>
-- 
Nizar Habash

**Comment by Linah-Bakhsh** [comment]
That was very helpful thank u so much
