### ISSUE TITLE
can't download the data required

### ISSUE THREAD

**Issue by lupangdesaili** [CAMeL-Lab/camel_tools#45]
mac-os catalina 10.15.7
I run the command for downloading required data in my terminal but it didn't return anything for long time until an error turned out as below:
(base) MacBook-Pro-3:camel_tools username$ camel_data full
Error: An error occured while downloading data.

I tried it with a vpn but it still doesn't work

**Comment by owo** [comment]
Hi @lupangdesaili,

Can you please try running `camel_data light` and let me know if you get the same issue?
Also, please run `python -VV` and paste the results here.
Can you tell me how was Python installed (default macOS, homebrew, pyenv, etc.)?

**Comment by lupangdesaili** [comment]
I tired camel_data light and it helps. Thank you

**Comment by ZRasouli** [comment]
I need to install the data package (already have camel_tools installed). How can I do that? It says in the installation instruction to run camel_data full, but should I do that in the command prompt?

**Comment by MMamdouh96** [comment]
i got the same error in ubuntu with python 3.6.6 (camel-tools==1.2.0)
 camel_data full
Error: An error occured while extracting downloaded data.

**Comment by owo** [comment]
Can you please upgrade to camel-tools 1.3.1? However, we only support Python 3.7+ as Python 3.6 has reached end-of-life.
Also, downloading data works a bit differently now, you'll have to run `camel_data -i all` instead.
