### ISSUE TITLE
[BUG] Incorrect Lemmatization of "يارب"

### ISSUE THREAD

**Issue by rrpelgrim** [CAMeL-Lab/camel_tools#46]
**Describe the bug**
The substring "يارب" is currently being tokenised as one token (which is expected behaviour, since it doesn't include a whitespace). The token is then disambiguated as "يأرب" using all schemes (except 'bwtok' which outputs "ي+_أرب"). The lemma in the most likely analysis (using the MLEDisambiguator) is أَرِب, however. Shouldn't that just be "رب"?

**To Reproduce**
Steps to reproduce the behavior.
Provide any Python/Shell scripts as code blocks.

```
sentence = ' يارب سوره بالتوفيق يارب اوقاف القران'

simple_word_tokenize(sentence)
mle = MLEDisambiguator.pretrained()
disambig = mle.disambiguate(sentence)

lemmas = [d.analyses[0].analysis['lex'] for d in disambig]
print(lemmas)
```

**Expected behavior**
Expect "يارب" to be lemmatized as "رب"

**Screenshots**
Preferably, attach error logs in code blocks.

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.4
 - Python version 3.7
 - CAMeL Tools version: pip v. 1.1.0

**Additional context**
This is my first time executing Arabic NLP, so if I'm overlooking something or should be posting this elsewhere, please do let me know!

**Comment by owo** [comment]
Hi @rrpelgrim,

Sorry for the delayed response.

So you are currently using the MSA MLEDisambiguator/Analyzer which do have some tolerance to errors, they do not include the attached 'يا'.

You may want to try using the Egyptian models, which do handle this case, by doing:
```python
mle = MLEDisambiguator.pretrained('calima-egy-r13')
``` 

I hope that helps.

**Comment by rrpelgrim** [comment]
Hi @owo, thanks! I ended up separating the "يا" from the "رب" using a regex - but will keep this in my mind for future use.
