### ISSUE TITLE
[ENHANCEMENT] Running MLEDisambiguator on AWS Cluster

### ISSUE THREAD

**Issue by rrpelgrim** [CAMeL-Lab/camel_tools#47]
**What feature would you like to improve?**
MLEDisambiguator

**Is your enhancement request related to a problem? Please describe.**
It's currently not possible to run the Disambiguator on a distributed system because it uses a local morphology.db file stored in the root directory. This file is not distributed to the workers on my AWS cluster.

**Describe the solution you'd like**
I'd like to be able to run the Disambiguator on my AWS cluster to speed up processing.

**Comment by owo** [comment]
Hi @rrpelgrim,

You probably need to run `camel_data` on each of your AWS instances but I don't know the details of your setup to give you a precise answer.

If you are only using the disambiguator, you could run `camel_data light` which would greatly reduce the amount of data you need to download at each node compared to running `camel_data full`.

One other approach is, if your workers have a shared mounted file system (EFS), you could always [set the $CAMELTOOLS_DATA environment variable](https://github.com/CAMeL-Lab/camel_tools#installing-data) to be somewhere in that file system before running `camel_data`.

Furthermore, any distributed implementation would still require a copy of the data to be present at each node one way or another.

**Comment by rrpelgrim** [comment]
Hi @owo, thanks for the quick and helpful response. Running `camel_data light` on each node seems to be doing the trick!
