### ISSUE TITLE
camel_tools.morphology.errors.DatabaseParseError: Error parsing database (invalid ORDER line '###STEMBACKOFF###')[BUG] Title of new issue...

### ISSUE THREAD

**Issue by Hamiedamr** [CAMeL-Lab/camel_tools#53]
**Describe the bug**
When I try morphology example from docs I got this bug
**To Reproduce**
I copied the example code and just run the python file.

**Expected behavior**
I expected to get the morphological analysis output
**Screenshots**
![issue](https://user-images.githubusercontent.com/23465012/121575609-de79ed80-ca27-11eb-9038-c2ad4341a1c2.JPG)
**Desktop (please complete the following information):**
 - Windows 10
 - Python 3.7
 - CAMeL Tools latest version and all data downloaded

**Comment by owo** [comment]
Hi @Hamiedamr,

Did you install camel-tools from pip or from source?

**Comment by firas-jolha** [comment]
Hello,
I'm getting similar db error?!!
I've installed `camel-tools` using `pip`, should it download the db while executing the code?


 `>>> mle_msa = MLEDisambiguator.pretrained('calima-msa-r13') `

 Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/camel_tools/disambig/mle.py", line 165, in pretrained
    analyzer = _MLE_ANALYZER_MAP[model_info.name]()
  File "/usr/local/lib/python3.8/dist-packages/camel_tools/disambig/mle.py", line 44, in _calima_msa_r13_analyzer
    db = MorphologyDB.builtin_db('calima-msa-r13', 'a')
  File "/usr/local/lib/python3.8/dist-packages/camel_tools/morphology/database.py", line 94, in builtin_db
    return MorphologyDB(str(Path(db_info.path, 'morphology.db')), flags)
  File "/usr/local/lib/python3.8/dist-packages/camel_tools/morphology/database.py", line 144, in __init__
    self._parse_dbfile(fpath)
  File "/usr/local/lib/python3.8/dist-packages/camel_tools/morphology/database.py", line 183, in _parse_dbfile
    with open(fpath, 'r', encoding='utf-8') as dbfile:
FileNotFoundError: [Errno 2] No such file or directory: '/home/firasj/.camel_tools/data/morphology_db/calima-msa-r13/morphology.db'

**Comment by owo** [comment]
Hi @firas-jolha 

Data installation is a [separate step](https://github.com/CAMeL-Lab/camel_tools#installing-data).
Can you try running `camel-data light` and retrying?

**Comment by Maroussia** [comment]
Hi, 
I am getting the same DatabaseParseError: Error parsing database (invalid ORDER line '###STEMBACKOFF###').
I installed from the source, and tried with both camel_data full and light.
Any news on how to fix it?
Thanks a lot!

- Ubuntu 21.04
- Python 3.8.5
- camel-tools 1.1.0

**Comment by ghaddarAbs** [comment]
@owo There is a bug in 
https://github.com/CAMeL-Lab/camel_tools/blob/90aa666a725d47b80b2309fe82d2db4d23e52871/camel_tools/morphology/database.py#L227

`morphology.db` has no `TOKENIZATIONS` attribute, here are the attribute that exists

```
###DEFINES###
###DEFAULTS###
###ORDER###
###STEMBACKOFF###
###PREFIXES###
###SUFFIXES###
###STEMS###
###TABLE AB###
###TABLE BC###
###TABLE AC###
```
A hack solution is to replace `TOKENIZATIONS` by `STEMBACKOFF` at line 227; and the comment the lines from https://github.com/CAMeL-Lab/camel_tools/blob/90aa666a725d47b80b2309fe82d2db4d23e52871/camel_tools/morphology/database.py#L268 to https://github.com/CAMeL-Lab/camel_tools/blob/90aa666a725d47b80b2309fe82d2db4d23e52871/camel_tools/morphology/database.py#L288

OR @owo, if you can please upload the new `morphology.db` that contains the `TOKENIZATIONS` 

Anyone, feel free to open a pull request if you find the solution useful

**Comment by owo** [comment]
Issue should now be fixed with the latest camel tools release.
Please reinstall camel_tools and the data files:

```
pip install camel-tools --upgrade

camel_data full

# or
camel_data light
```

**Comment by djxd28** [comment]
hello 
it's not working even with 
pip install camel-tools --upgrade

camel_data full

# or
camel_data light

still there is an error of FileNotFoundError: [Errno 2] No such file or directory: '/root/.camel_tools/data/morphology_db/calima-msa-r13/morphology.db'

related to this >>> mle_msa = MLEDisambiguator.pretrained('calima-msa-r13')
