### ISSUE TITLE
dediacritizing Arabic text question

### ISSUE THREAD

**Issue by AFA-eng** [CAMeL-Lab/camel_tools#55]
I want to remove tanween Fath + Alif , In the following code 
```
sentence_ar = 'اشتريت كتبًا كثيرةً'

sentence_ar_dediac = dediac_ar(sentence_ar)

print(sentence_ar_dediac))
```

the output is
`	اشتريت كتبا كثيرة
`
Is there a way to remove Alif so the output will be
`	اشتريت كتب كثيرة
`

I want to apply this feature to many words in my dataset.

**Comment by slkh** [comment]
Interesting question. To do this, you need to first disambiguate the Arabic as the word `كتبا` could be the dual perfective verb `كَتَبا` _they wrote_ or the accusative noun `كُتُباً` _books_. As such, we recommend the following to be able to remove the Alif consistently:

1.  Disambiguate the text using the currently available MLE-based disambiguation (`camel_tools.disambig.mle`) : https://camel-tools.readthedocs.io/en/latest/api/disambig/mle.html
2. The disambiguation will produce the Tanween Fath in the style of Alif+Fathataan consistently, you will then have to just look for `اً` and remove it.
3. Run `dediac_ar` on the text as you would normally do.

Here is a minimum working example of the above steps:

```python
import re
from camel_tools.utils.dediac import dediac_ar
from camel_tools.disambig.mle import MLEDisambiguator

mle = MLEDisambiguator.pretrained()

sentence_ar = 'اشتريت كتبًا كثيرةً'

disambig = mle.disambiguate(sentence_ar.split(' '))

diacritized_tokens = [d.analyses[0].analysis['diac'] for d in disambig]
#Result: ['اِشْتَرَيْتُ', 'كُتُباً', 'كَثِيرَةٍ']

diacritized_sentence_ar = ' '.join(diacritized_tokens)
#Result: 'اِشْتَرَيْتُ كُتُباً كَثِيرَةٍ'

#remove Alif+Fathatan
undiacritized_sentence_ar = re.sub('اً', '', diacritized_sentence_ar)
#Result: 'اِشْتَرَيْتُ كُتُب كَثِيرَةٍ'

#remove all other diacritics
undiacritized_sentence_ar = dediac_ar(undiacritized_sentence_ar)
#Result: 'اشتريت كتب كثيرة'
```

**Comment by AFA-eng** [comment]
OK , I understand now.

but there is an error with
`mle = MLEDisambiguator.pretrained()`

```
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-6-335c890545c7> in <module>()
----> 1 mle = MLEDisambiguator.pretrained()

4 frames
/usr/local/lib/python3.7/dist-packages/camel_tools/morphology/database.py in _parse_dbfile(self, fpath)
    181 
    182     def _parse_dbfile(self, fpath):
--> 183         with open(fpath, 'r', encoding='utf-8') as dbfile:
    184             # Process DEFINES
    185             for line in dbfile:

FileNotFoundError: [Errno 2] No such file or directory: '/root/.camel_tools/data/morphology_db/calima-msa-r13/morphology.db'

```

**Comment by slkh** [comment]
You need to install `camel_data` as described here: https://github.com/CAMeL-Lab/camel_tools#installing-data

**Comment by AFA-eng** [comment]
I got it.
جزاك الله خير
