### ISSUE TITLE
camel_tools.morphology.errors

### ISSUE THREAD

**Issue by KarmelShehadeh** [CAMeL-Lab/camel_tools#58]
**Describe the bug**
 When I try Morphological analysis example that exists in (CAMeL_Tools_Guided_Tour.ipynb) I got this bug.
**To Reproduce** 
I copied the example code from the guide and just run the python file.
**Expected behavior**
 I expected to get the morphological analysis output

**Screenshots**
If applicable, add scre
![Screenshot from 2021-07-29 21-51-18](https://user-images.githubusercontent.com/35188216/127549512-eb3a90c7-9f37-4eab-856f-2c882e50550f.png)
enshots to help explain your problem.
Preferably, attach error logs in code blocks.

**Desktop (please complete the following information):**
 - OS [Ubuntu 20.04.2 LTS ]
 - Python 3.8.5
 - CAMeL Tools latest version and all data downloaded using pip3
- i downloaded camel data using (camel_data full) command

**Comment by owo** [comment]
Latest release should fix this issue.
Please reinstall camel_tools and the data files by running:

```
pip install camel-tools --upgrade
camel_data full
```

Please let me know if you still face any issues.
