### ISSUE TITLE
[BUG] Estraction error when updating CAMeL data

### ISSUE THREAD

**Issue by lancioni** [CAMeL-Lab/camel_tools#62]
After updating camel_tools to version 1.2.0 (Windows 10, Python 3.6), the following error is produced after_running camel_data full:

Error: An error occured while extracting downloaded data.

However, camel_data light runs with no errors.

**Comment by owo** [comment]
See [here](https://github.com/CAMeL-Lab/camel_tools/issues/61#issuecomment-900027526).
I'll look into other ways to host the data packages but the sudden influx of users was not expected.

**Comment by lancioni** [comment]
Ok, thanks!
