### ISSUE TITLE
[QUESTION]  Error while loading sentiment_analysis/arabert model

### ISSUE THREAD

**Issue by JayR7** [CAMeL-Lab/camel_tools#63]
Greetings, 
It seems that there's a similar issue that has been closed before, but unfortunately the suggested solutions didn't work in my case.
**When trying to load AraBERT model:**

```sa = SentimentAnalyzer.pretrained()

sentences = [
    'أنا بخير',
    'ابشرك'
]
sentiments = sa.predict(sentences)```

**I get the following error while:**

OSError: Can't load config for '/Users/.../.camel_tools/data/sentiment_analysis/arabert'. Make sure that:

- '/Users/.../.camel_tools/data/sentiment_analysis/arabert' is a correct model identifier listed on 'https://huggingface.co/models'

- or '/Users/.../.camel_tools/data/sentiment_analysis/arabert' is the correct path to a directory containing a config.json file

Your assistance is greatly appreciated, thanks in advance!

**Comment by owo** [comment]
Hi @JayR7 ,

Can you please run `ls -R ~/.camel_tools` on a terminal and share the output?

**Comment by JayR7** [comment]
[](url)> Hi @JayR7 ,
> 
> Can you please run `ls -R ~/.camel_tools` on a terminal and share the output?

Hi, thanks for your prompt response!

![Screenshot 2021-08-31 at 12 05 02](https://user-images.githubusercontent.com/52196205/131474957-9152db49-4d2b-40e8-838c-d06b54aa86b4.png)

Hope I've provided the info you're looking for.

**Comment by owo** [comment]
Hi @JayR7 ,

Please copy and paste the above command as is into the terminal.
You seem to have run `ls camel_tools` within the `camel_tools` source directory.
You should not be getting an `__init__.py` for example.

**Comment by JayR7** [comment]
![Screenshot 2021-08-31 at 13 51 47](https://user-images.githubusercontent.com/52196205/131490483-d2e935ef-254b-4ad7-a410-588247c0459a.png)

**Comment by owo** [comment]
You ran `ls -R camel_tools`.
Please run `ls -R ~/.camel_tools`.
Copy and paste it exactly please.
Even if it generates an error, just share the error.

**Comment by JayR7** [comment]
Yes, actually running `ls -R ~/.camel_tools` command doesn't show any output. 

![Screenshot 2021-08-31 at 14 14 59](https://user-images.githubusercontent.com/52196205/131493998-a2da4652-21e3-4174-8519-644120d49138.png)

**Comment by owo** [comment]
Perfect. That means you haven't installed the camel tools data.
Please follow the [data installation instructions](https://github.com/CAMeL-Lab/camel_tools#installing-data) and let me know how it goes.

**Comment by JayR7** [comment]
Hi @owo , hope you're having a delightful day.
Sorry but when i run `camel-data full` command on the terminal, i got "command not found" output, even though camel_tools library is already installed.
i guess i'm missing a step?

**Comment by owo** [comment]
Hi @JayR7 ,

The command is `camel_data full` not `camel-data full`.
I hope that helps.

**Comment by JayR7** [comment]
Yes, sorry i 've mistakenly typed a dash.
I actually have ran `camel_data full`

**Comment by owo** [comment]
The problem is you don't have the `PATH` environment variable properly set to find command line tools installed through pip.
Running `python -m camel_tools.cli.camel_data full` should be a quick workaround for now, but you should set it up correctly later for convenience.
Doing so will depend on how you installed Python (pyenv, homebrew, anaconda, etc) and what shell you are using (bash, zsh, etc) and is beyond the support we provide.

**Comment by JayR7** [comment]
No problem at all, thanks a lot Ossama for your time!
