### ISSUE TITLE
[QUESTION] PoS feature Enhancement request

### ISSUE THREAD

**Issue by KarmelShehadeh** [CAMeL-Lab/camel_tools#72]
**Describe what you would like to know about CAMeL Tools.**
PoS feature Enhancement request, especially for foreign words tag.
When i using tagger function with non Arabic words it always tag it as 'noun'. Based on your guide it must tag as 'FORIEGN'

**Iam using this code:**
`from camel_tools.tokenizers.word import simple_word_tokenize
from camel_tools.disambig.mle import MLEDisambiguator
from camel_tools.tagger.default import DefaultTagger

mle = MLEDisambiguator.pretrained()
tagger = DefaultTagger(mle, 'pos')

sentence = simple_word_tokenize(' HTML استخدم')

pos_tags = tagger.tag(sentence)

print(pos_tags)`

**My question is were the problem? in my code or this feature need enhancement?**

**Comment by owo** [comment]
This issue has been fixed now.
