### ISSUE TITLE
[BUG] PicklingError when pickling MLEDisambiguator

### ISSUE THREAD

**Issue by manuelvloureiro** [CAMeL-Lab/camel_tools#75]
**Describe the bug**
PicklingError when pickling MLEDisambiguator

**To Reproduce**

    from camel_tools.disambig.mle import MLEDisambiguator
    import pickle

    d = MLEDisambiguator.pretrained()
    pickle.dump(d, 'file.pkl')

**Expected behavior**
A saved pickled file that can later be loaded.

**Comment by owo** [comment]
This should now be doable in the latest release.
