### ISSUE TITLE
[BUG] error installing camel-tools on python 3.7 and 3.8

### ISSUE THREAD

**Issue by fadhleryani** [CAMeL-Lab/camel_tools#77]
**Describe the bug**
I use camel-tools (v1.1) in my romanize arabic ala-lc project, which was done using python 3.7.  While trying to install my app in a fresh python 3.7 environment, I discovered camel-tools installation gives an error.  I tried 3.8 environment and similar error occurs.  Python 3.9 seems to install with no issues.  The error does not seem to be specific to version 1.1.

**To Reproduce**
pip install camel-tools==1.1 
(but also pip install camel-tools without version)

**Screenshots**
`Collecting camel-tools==1.1
  Using cached camel_tools-1.1.0-py3-none-any.whl
Collecting dill
  Using cached dill-0.3.4-py2.py3-none-any.whl (86 kB)
Collecting camel-kenlm
  Using cached camel-kenlm-2021.12.27.tar.gz (418 kB)
Collecting transformers==3.0.2
  Using cached transformers-3.0.2-py3-none-any.whl (769 kB)
Collecting scikit-learn
  Using cached scikit_learn-1.0.2-cp37-cp37m-macosx_10_13_x86_64.whl (7.8 MB)
Collecting six
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting torch>=1.3
  Using cached torch-1.10.1-cp37-none-macosx_10_9_x86_64.whl (147.1 MB)
Collecting numpy
  Using cached numpy-1.21.5-cp37-cp37m-macosx_10_9_x86_64.whl (16.9 MB)
Collecting docopt
  Using cached docopt-0.6.2-py2.py3-none-any.whl
Collecting scipy
  Using cached scipy-1.7.3-cp37-cp37m-macosx_10_9_x86_64.whl (33.0 MB)
Collecting editdistance
  Using cached editdistance-0.6.0-cp37-cp37m-macosx_10_9_x86_64.whl (21 kB)
Collecting requests
  Using cached requests-2.27.0-py2.py3-none-any.whl (63 kB)
Collecting cachetools
  Using cached cachetools-5.0.0-py3-none-any.whl (9.1 kB)
Collecting future
  Using cached future-0.18.2-py3-none-any.whl
Collecting pandas
  Using cached pandas-1.3.5-cp37-cp37m-macosx_10_9_x86_64.whl (11.0 MB)
Collecting tokenizers==0.8.1.rc1
  Using cached tokenizers-0.8.1rc1-cp37-cp37m-macosx_10_10_x86_64.whl (2.1 MB)
Collecting packaging
  Using cached packaging-21.3-py3-none-any.whl (40 kB)
Collecting sentencepiece!=0.1.92
  Using cached sentencepiece-0.1.96-cp37-cp37m-macosx_10_6_x86_64.whl (1.1 MB)
Collecting filelock
  Using cached filelock-3.4.2-py3-none-any.whl (9.9 kB)
Collecting sacremoses
  Using cached sacremoses-0.0.46-py3-none-any.whl (895 kB)
Collecting regex!=2019.12.17
  Using cached regex-2021.11.10-cp37-cp37m-macosx_10_9_x86_64.whl (288 kB)
Collecting tqdm>=4.27
  Using cached tqdm-4.62.3-py2.py3-none-any.whl (76 kB)
Collecting typing-extensions
  Using cached typing_extensions-4.0.1-py3-none-any.whl (22 kB)
Collecting pyparsing!=3.0.5,>=2.0.2
  Using cached pyparsing-3.0.6-py3-none-any.whl (97 kB)
Collecting pytz>=2017.3
  Using cached pytz-2021.3-py2.py3-none-any.whl (503 kB)
Collecting python-dateutil>=2.7.3
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/Caskroom/miniconda/base/envs/test-camel/lib/python3.7/site-packages (from requests->camel-tools==1.1) (2021.10.8)
Collecting idna<4,>=2.5
  Using cached idna-3.3-py3-none-any.whl (61 kB)
Collecting charset-normalizer~=2.0.0
  Using cached charset_normalizer-2.0.9-py3-none-any.whl (39 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.7-py2.py3-none-any.whl (138 kB)
Collecting joblib
  Using cached joblib-1.1.0-py2.py3-none-any.whl (306 kB)
Collecting click
  Using cached click-8.0.3-py3-none-any.whl (97 kB)
Collecting importlib-metadata
  Using cached importlib_metadata-4.10.0-py3-none-any.whl (17 kB)
Collecting zipp>=0.5
  Using cached zipp-3.7.0-py3-none-any.whl (5.3 kB)
Collecting threadpoolctl>=2.0.0
  Using cached threadpoolctl-3.0.0-py3-none-any.whl (14 kB)
Building wheels for collected packages: camel-kenlm
  Building wheel for camel-kenlm (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/local/Caskroom/miniconda/base/envs/test-camel/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/33/0wcrq6q95r1c11srbk4x2yzm0000gn/T/pip-install-len8q7si/camel-kenlm_b11ec25ad31545fcb1d7392ddbd4efdf/setup.py'"'"'; __file__='"'"'/private/var/folders/33/0wcrq6q95r1c11srbk4x2yzm0000gn/T/pip-install-len8q7si/camel-kenlm_b11ec25ad31545fcb1d7392ddbd4efdf/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/33/0wcrq6q95r1c11srbk4x2yzm0000gn/T/pip-wheel-yk0q8tf2
       cwd: /private/var/folders/33/0wcrq6q95r1c11srbk4x2yzm0000gn/T/pip-install-len8q7si/camel-kenlm_b11ec25ad31545fcb1d7392ddbd4efdf/
  Complete output (13 lines):
  running bdist_wheel
  running build
  running build_ext
  building 'kenlm' extension
  creating build
  creating build/temp.macosx-10.9-x86_64-3.7
  creating build/temp.macosx-10.9-x86_64-3.7/util
  creating build/temp.macosx-10.9-x86_64-3.7/lm
  creating build/temp.macosx-10.9-x86_64-3.7/util/double-conversion
  creating build/temp.macosx-10.9-x86_64-3.7/python
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/local/Caskroom/miniconda/base/envs/test-camel/include -arch x86_64 -I/usr/local/Caskroom/miniconda/base/envs/test-camel/include -arch x86_64 -I. -I/usr/local/Caskroom/miniconda/base/envs/test-camel/include/python3.7m -c util/pool.cc -o build/temp.macosx-10.9-x86_64-3.7/util/pool.o -O3 -DNDEBUG -DKENLM_MAX_ORDER=6 -std=c++11 -stdlib=libc++ -mmacosx-version-min=10.7 -DHAVE_ZLIB -DHAVE_BZLIB
  gcc: error: unrecognized command-line option '-stdlib=libc++'
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for camel-kenlm
  Running setup.py clean for camel-kenlm
Failed to build camel-kenlm
Installing collected packages: zipp, typing-extensions, importlib-metadata, urllib3, tqdm, six, regex, pyparsing, numpy, joblib, idna, click, charset-normalizer, tokenizers, threadpoolctl, sentencepiece, scipy, sacremoses, requests, pytz, python-dateutil, packaging, filelock, transformers, torch, scikit-learn, pandas, future, editdistance, docopt, dill, camel-kenlm, cachetools, camel-tools
    Running setup.py install for camel-kenlm ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/local/Caskroom/miniconda/base/envs/test-camel/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/33/0wcrq6q95r1c11srbk4x2yzm0000gn/T/pip-install-len8q7si/camel-kenlm_b11ec25ad31545fcb1d7392ddbd4efdf/setup.py'"'"'; __file__='"'"'/private/var/folders/33/0wcrq6q95r1c11srbk4x2yzm0000gn/T/pip-install-len8q7si/camel-kenlm_b11ec25ad31545fcb1d7392ddbd4efdf/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/33/0wcrq6q95r1c11srbk4x2yzm0000gn/T/pip-record-me6kza5t/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/Caskroom/miniconda/base/envs/test-camel/include/python3.7m/camel-kenlm
         cwd: /private/var/folders/33/0wcrq6q95r1c11srbk4x2yzm0000gn/T/pip-install-len8q7si/camel-kenlm_b11ec25ad31545fcb1d7392ddbd4efdf/
    Complete output (13 lines):
    running install
    running build
    running build_ext
    building 'kenlm' extension
    creating build
    creating build/temp.macosx-10.9-x86_64-3.7
    creating build/temp.macosx-10.9-x86_64-3.7/util
    creating build/temp.macosx-10.9-x86_64-3.7/lm
    creating build/temp.macosx-10.9-x86_64-3.7/util/double-conversion
    creating build/temp.macosx-10.9-x86_64-3.7/python
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/local/Caskroom/miniconda/base/envs/test-camel/include -arch x86_64 -I/usr/local/Caskroom/miniconda/base/envs/test-camel/include -arch x86_64 -I. -I/usr/local/Caskroom/miniconda/base/envs/test-camel/include/python3.7m -c util/pool.cc -o build/temp.macosx-10.9-x86_64-3.7/util/pool.o -O3 -DNDEBUG -DKENLM_MAX_ORDER=6 -std=c++11 -stdlib=libc++ -mmacosx-version-min=10.7 -DHAVE_ZLIB -DHAVE_BZLIB
    gcc: error: unrecognized command-line option '-stdlib=libc++'
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/Caskroom/miniconda/base/envs/test-camel/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/33/0wcrq6q95r1c11srbk4x2yzm0000gn/T/pip-install-len8q7si/camel-kenlm_b11ec25ad31545fcb1d7392ddbd4efdf/setup.py'"'"'; __file__='"'"'/private/var/folders/33/0wcrq6q95r1c11srbk4x2yzm0000gn/T/pip-install-len8q7si/camel-kenlm_b11ec25ad31545fcb1d7392ddbd4efdf/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/33/0wcrq6q95r1c11srbk4x2yzm0000gn/T/pip-record-me6kza5t/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/Caskroom/miniconda/base/envs/test-camel/include/python3.7m/camel-kenlm Check the logs for full command output.`

**Desktop (please complete the following information):**
 - OS: macOS 11.5.2
 - Python 3.7
 - CAMel tools 1.1 installed on pip

**Additional context**
The error was discovered while trying to redeploy my romanization app on gcloud, which kept failing because deployment time surprassed the 10 minute limit.

**Comment by MMamdouh96** [comment]
I have the same issue on python3.7 , did you got the solution?

**Comment by owo** [comment]
Hi @MMamdouh96 
Can you please what OS and OS version you are running on?
Also please paste the full log as above?

**Comment by owo** [comment]
@fadhleryani 

Sadly we can't help with 1.1 at this point.
Can you try upgrading to 1.3.1?

**Comment by pelchafei** [comment]
I have the same error, any hints?
