### ISSUE TITLE
[BUG] error while installing camel_tool on Colab python 3.7

### ISSUE THREAD

**Issue by esulaiman** [CAMeL-Lab/camel_tools#78]
**Describe the bug**
I tried to run the following pip command on Colab with python 3.7 version: 
!pip install camel-tools
!camel_data full

Usually it works fine but today it gave me the following error message:
Error: An error occured while extracting downloaded data.

I could assume this error happened due to exceeded server requests. 

Can yon kindly help me with this issue.

Thanks in advance.

**Comment by aosaimy** [comment]
> The issue seems to be that a Google Drive is blocking the download since the file is too big and thus the antivirus cannot be applied:
> 
> ![image](https://user-images.githubusercontent.com/17943873/155890696-d4ef813a-e63d-4f9d-aeec-5a6be8ce0042.png)
> 
> The current workaround I found is to download the file (URL: https://docs.google.com/uc?export=download&id=1wznZY1nXIwKan5rLbvQjukozNrF-P0j3 ) using the browser or the python package `gdown` and then unzip it in `~/.camel_tools`

**Comment by owo** [comment]
We have pushed a fix for the issue.
The *Guided Tour* Colab notebook has now changed so you may have to start with the updated one if you made any changes to the old one.
