### ISSUE TITLE
AppData\Roaming\camel_tools\data\data\sentiment_analysis\arabert is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'[QUESTION] Title of question...

### ISSUE THREAD

**Issue by sawalzubi** [CAMeL-Lab/camel_tools#79]
Hello, I am trying to test sentiment analysis tools using CAMeL.  I tried to implement the following code:
`from camel_tools.sentiment import SentimentAnalyzer

sa = SentimentAnalyzer.pretrained()

sentences = [
    'أنا بخير',
    'أنا لست بخير'
]

sentiments = sa.predict(sentences)

print(sentiments)`

Where this error kept occurring 
OSError: C:\Users\s.alzubi\AppData\Roaming\camel_tools\data\data\sentiment_analysis\arabert is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo with `use_auth_token` or log in with `huggingface-cli login` and pass `use_auth_token=True`.  

I spent a week solving this problem, tried to create a username on Huggingface and generated an access token to execute the code. Then I got stuck with this and couldn't do anything.
Can anyone help me with this?
thank you

**Comment by owo** [comment]
@balhafni it seems the arabert models have been moved to a new repo. Can you look into this?

**Comment by balhafni** [comment]
@sawalzubi we're aware of the issue. We are currently working on a new download manager and it should be ready within a week.

**Comment by owo** [comment]
We have pushed a fix for the issue.
Please upgrade camel-tools by running `pip install --upgrade camel-tools`.
The data installation command is slightly different now so you have to run either `camel_data -i all` or `camel_data -i light`.
