### ISSUE TITLE
[BUG] Error: An error occured while extracting downloaded data. Windows 10

### ISSUE THREAD

**Issue by amrelnagar286** [CAMeL-Lab/camel_tools#80]
Hello Camel Team, hope you're having a delightful day.

I installed the latest Camel tools (Version 1.2.0) on Windows 10 machine, using the command `pip install camel-tools -f https://download.pytorch.org/whl/torch_stable.html`.

Then I'm trying to install camel's full data by using `camel_data full` or `python -m camel_tools.cli.camel_data full` command, and suddenly getting an error message says: `Error: An error occured while extracting downloaded data.`

When trying to install the light version of data using `camel_data light`, it works without facing any problems.

Could you please let me know where I am missing a step?

**Expected behavior**
It was expected to start installing a full 1.8 GB of Camel's full data.

**Screenshots**
```
(base) PS C:\Users\me> camel_data full
Error: An error occured while extracting downloaded data.
```

**Desktop (please complete the following information):**
 - OS [Windows 10, Version: 21H1, 64bit]
 - Python version: 3.9 Anaconda3, 3.10 installed locally.
 - CAMeL Tools version as well as installation source (1.2.0, source).

**Additional context**
![image](https://user-images.githubusercontent.com/52659036/154745960-b814b156-9dfb-4e7d-901a-4552fcb8416e.png)

**Comment by balhafni** [comment]
We're aware of the issue. We are currently working on a new download manager and it should be ready within a week.

**Comment by etiennekintzler** [comment]
The issue seems to be that a Google Drive is blocking the download since the file is too big and thus the antivirus cannot be applied:

![image](https://user-images.githubusercontent.com/17943873/155890696-d4ef813a-e63d-4f9d-aeec-5a6be8ce0042.png)

The current workaround might be to download the file through the browser using the following URL: https://docs.google.com/uc?export=download&id=1wznZY1nXIwKan5rLbvQjukozNrF-P0j3

**Comment by owo** [comment]
We have pushed a fix for the issue.
Please upgrade camel-tools by running `pip install --upgrade camel-tools`.
The data installation command is slightly different now so you have to run either `camel_data -i all` or `camel_data -i light`.
