### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/root/.camel_tools/data/morphology_db/calima-msa-r13/morphology.db'

### ISSUE THREAD

**Issue by Nouf96** [CAMeL-Lab/camel_tools#82]
I am working on a project, and I want to use the Camel toolkit to perform NLP tasks. I have already installed the camel tools; I am working on google Collab, but I faced this problem. 
FileNotFoundError: [Errno 2] No such file or directory: '/root/.camel_tools/data/morphology_db/calima-msa-r13/morphology.db'
 diffrents solusions have been tried as you mentioned on other issues like pip install --upgrade
camel_data full or
camel_data light but still not working 
Awaiting for your kind reply.
thank you in advance

**Comment by aosaimy** [comment]
> The issue seems to be that a Google Drive is blocking the download since the file is too big and thus the antivirus cannot be applied:
> 
> ![image](https://user-images.githubusercontent.com/17943873/155890696-d4ef813a-e63d-4f9d-aeec-5a6be8ce0042.png)
> 
> The current workaround I found is to download the file (URL: https://docs.google.com/uc?export=download&id=1wznZY1nXIwKan5rLbvQjukozNrF-P0j3 ) using the browser or the python package `gdown` and then unzip it in `~/.camel_tools`

**Comment by owo** [comment]
We are aware of this issue and we're working on a new downloader to move away from Google Drive.
It should be out soon.
