### ISSUE TITLE
[BUG] Issue with full data again

### ISSUE THREAD

**Issue by lancioni** [CAMeL-Lab/camel_tools#87]
**Describe the bug**
As it already happened, camel_data full gives the error:
Error: An error occured while extracting downloaded data.

camel_data light works fine.
If I remember well, it was an issue with space in the server where data are hosted.

**To Reproduce**
camel_data full

**Expected behavior**

**Screenshots**
Preferably, attach error logs in code blocks.

**Desktop (please complete the following information):**
 - OS [e.g. Windows, macOS, Linux, etc] along with OS version
 - Python version
 - CAMeL Tools version as well as installation source (pip, conda, source). If installed from source, specify which branch [e.g. master] and/or commit hash.

**Additional context**

**Comment by owo** [comment]
Hi @lancioni 

Can you please upgrade camel_tools and reinstall the data using the instructions in [this reponse](https://github.com/CAMeL-Lab/camel_tools/issues/83#issuecomment-1082647967).
We upgraded our data downloader and moved away from Google Drive for hosting our data files (which is what's causing these issues).
