### ISSUE TITLE
Some morphological data disappeared

### ISSUE THREAD

**Issue by lancioni** [CAMeL-Lab/camel_tools#89]
After recompiling version 1.4.0 under Python 3.9, some morphological data are missing from disambiguation. in particularly, such data as atbdok , caphi or ud are no longer there. An example:

{'diac': 'اِسْتِخْباراتِ',
 'lex': 'ٱِسْتِخْبار',
 'bw': 'ٱِسْتِخْبار/NOUN+ات/NSUFF_FEM_PL+ِ/CASE_DEF_GEN',
 'gloss': 'intelligence;secret_service;inquiry_[ARAMORPH]+[fem.pl.]_[ARAMORPH]',
 'pos': 'noun',
 'prc3': '0',
 'prc2': '0',
 'prc1': '0',
 'prc0': '0',
 'per': 'na',
 'asp': 'na',
 'vox': 'na',
 'mod': 'na',
 'gen': 'f',
 'num': 'p',
 'stt': 'c',
 'cas': 'g',
 'enc0': '0',
 'enc1': '0',
 'enc2': '0',
 'rat': 'y',
 'source': 'lex',
 'form_gen': 'f',
 'form_num': 'p',
 'bwtok': 'ٱِسْتِخْبار_+ات_+ِ',
 'pos_logprob': -0.9991953329976189,
 'pos_lex_logprob': -99.0,
 'lex_logprob': -99.0,
 'stem': 'ٱِسْتِخْبار',
 'stemgloss': 'intelligence;secret_service;inquiry_[ARAMORPH]',
 'stemcat': 'NduAt'}

Perhaps something changed in a recent update?

Thank you?

Giuliano

**Comment by owo** [comment]
Hi @lancioni 

There was an error in our data catalogue that's now fixed.
You'll need to run the following to get the latest packages:

```
camel_data -u
camel_data -i -f morphology-db-all
```
