### ISSUE TITLE
[BUG] Egyptian db not loaded in Windows 10

### ISSUE THREAD

**Issue by lancioni** [CAMeL-Lab/camel_tools#92]
**Describe the bug**
camel_data -i all under Windows 10, Python 3.9, does not install Egyptian morphology data calima-egy-r13: only MSA and Gulf data are available.
If forced with -f option, it does declare that morphology-db-egy-r13 is installed, yet the data are not actually there. 

D:\corpora\tatoeba>camel_data -i -f all
The following packages will be installed: 'disambig-ranking-cache-calima-msa-r13', 'disambig-ranking-cache-calima-egy-r13', 'disambig-mle-calima-msa-r13', 'disambig-bert-unfactored-glf', 'morphology-db-egy-r13', 'ner-arabert', 'sentiment-analysis-mbert', 'dialectid-default', 'sentiment-analysis-arabert', 'disambig-ranking-cache-calima-glf-01', 'morphology-db-glf-01', 'disambig-mle-calima-egy-r13', 'disambig-bert-unfactored-egy', 'morphology-db-msa-r13', 'disambig-bert-unfactored-msa'
Downloading package 'disambig-ranking-cache-calima-msa-r13': 100%|███████| 519M/519M [00:33<00:00, 15.3MB/s] Extracting package 'disambig-ranking-cache-calima-msa-r13': 100%|█████████| 519M/519M [00:01<00:00, 304MB/s] Downloading package 'disambig-ranking-cache-calima-egy-r13': 100%|███████| 289M/289M [00:47<00:00, 6.07MB/s] Extracting package 'disambig-ranking-cache-calima-egy-r13': 100%|█████████| 289M/289M [00:00<00:00, 458MB/s] Downloading package 'disambig-mle-calima-msa-r13': 100%|███████████████| 88.7M/88.7M [00:06<00:00, 12.9MB/s] Extracting package 'disambig-mle-calima-msa-r13': 100%|█████████████████| 88.7M/88.7M [00:00<00:00, 544MB/s] Downloading package 'disambig-bert-unfactored-glf': 100%|████████████████| 442M/442M [00:33<00:00, 13.3MB/s] Extracting package 'disambig-bert-unfactored-glf': 100%|██████████████████| 442M/442M [00:01<00:00, 292MB/s] Downloading package 'morphology-db-egy-r13': 100%|█████████████████████| 67.3M/67.3M [00:04<00:00, 14.4MB/s] Extracting package 'morphology-db-egy-r13': 100%|███████████████████████| 67.3M/67.3M [00:00<00:00, 547MB/s] Downloading package 'ner-arabert': 100%|█████████████████████████████████| 542M/542M [00:39<00:00, 13.9MB/s] Extracting package 'ner-arabert': 100%|███████████████████████████████████| 542M/542M [00:01<00:00, 281MB/s] Downloading package 'sentiment-analysis-mbert': 100%|████████████████████| 712M/712M [00:54<00:00, 13.1MB/s] Extracting package 'sentiment-analysis-mbert': 100%|██████████████████████| 712M/712M [00:02<00:00, 276MB/s] Downloading package 'dialectid-default': 100%|███████████████████████████| 282M/282M [00:35<00:00, 7.97MB/s] Extracting package 'dialectid-default': 100%|█████████████████████████████| 282M/282M [00:00<00:00, 474MB/s] Downloading package 'sentiment-analysis-arabert': 100%|██████████████████| 542M/542M [00:43<00:00, 12.6MB/s] Extracting package 'sentiment-analysis-arabert': 100%|████████████████████| 542M/542M [00:01<00:00, 289MB/s] Downloading package 'disambig-ranking-cache-calima-glf-01': 100%|██████| 21.5M/21.5M [00:03<00:00, 7.11MB/s] Extracting package 'disambig-ranking-cache-calima-glf-01': 100%|████████| 21.5M/21.5M [00:00<00:00, 515MB/s] Downloading package 'morphology-db-glf-01': 100%|██████████████████████| 7.98M/7.98M [00:00<00:00, 14.7MB/s] Extracting package 'morphology-db-glf-01': 100%|████████████████████████| 7.98M/7.98M [00:00<00:00, 468MB/s] Downloading package 'disambig-mle-calima-egy-r13': 100%|███████████████| 27.2M/27.2M [00:01<00:00, 15.5MB/s] Extracting package 'disambig-mle-calima-egy-r13': 100%|█████████████████| 27.2M/27.2M [00:00<00:00, 531MB/s] Downloading package 'disambig-bert-unfactored-egy': 100%|████████████████| 446M/446M [00:49<00:00, 9.06MB/s] Extracting package 'disambig-bert-unfactored-egy': 100%|██████████████████| 446M/446M [00:01<00:00, 285MB/s] Downloading package 'morphology-db-msa-r13': 100%|█████████████████████| 40.5M/40.5M [00:02<00:00, 14.9MB/s] Extracting package 'morphology-db-msa-r13': 100%|███████████████████████| 40.5M/40.5M [00:00<00:00, 542MB/s] Downloading package 'disambig-bert-unfactored-msa': 100%|████████████████| 445M/445M [00:27<00:00, 16.0MB/s] Extracting package 'disambig-bert-unfactored-msa': 100%|██████████████████| 445M/445M [00:01<00:00, 283MB/s]

When I try to load the database
db = MorphologyDB.builtin_db('calima-egy-r13')

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Giuliano Lancioni\\AppData\\Roaming\\camel_tools\\data\\morphology_db\\calima-egy-r13\\morphology.db'

The Egyptian files are present in catalog.js, but they are not available on disk.

**Comment by owo** [comment]
Can you try updating the catalogue and reinstalling the Egyptianrunning the following 

```
camel_data -u
camel_data -i -f all
```

There was a bugged version of the catalogue at one point which we patched.
