### ISSUE TITLE
[BUG] camel_tools.disambig.bert

### ISSUE THREAD

**Issue by lancioni** [CAMeL-Lab/camel_tools#93]
**Describe the bug**
camel_tools.disambig.bert is not available under both Windows and Linux (Python 3.9)

**To Reproduce**
example in https://camel-tools.readthedocs.io/en/latest/api/disambig/bert.html

**Expected behavior**
Analysis.

Instead, the following message appears (example in Ubuntu 18.04):
camel_tools.data.catalogue.CatalogueError: Invalid component name 'DisambigBertUnfactored'.

**Comment by owo** [comment]
The error indicates that you may have an old catalogue installed (before the BERT model was introduced).
Please run the following to get the updated catalogue and packages

```
camel_data -u
camel_data -i -f all
```

**Comment by lancioni** [comment]
It works like a charm. Thank you!
