### ISSUE TITLE
[BUG] Run CAMeL on GPU now work

### ISSUE THREAD

**Issue by bdieaq** [CAMeL-Lab/camel_tools#94]
**Describe the bug**
I set SentimentAnalyzer.pretrained to take GPU but still using CPU

**To Reproduce**
Should using GPU instead of CPU

**Expected behavior**
Should using GPU instead of CPU.

**Comment by balhafni** [comment]
If you have the right cuda version that is compatible with the torch version you're using, the sentiment analyzer model will be placed on the GPU after calling `predict()`. Here's the code snippet that verifies this:

```python
from camel_tools.sentiment import SentimentAnalyzer

sentiment_analyzer = SentimentAnalyzer.pretrained() # use_gpu is True by default
predictions = sentiment_analyzer.predict(['أنا سعيد'])

print(sentiment_analyzer.model.device)
device(type='cuda', index=0)
```
