### ISSUE TITLE
[BUG] Can't Install Camel tools on Mac

### ISSUE THREAD

**Issue by uzairaj** [CAMeL-Lab/camel_tools#95]
**Describe the bug**
Can't install camel tools library on Mac..attaching screenshot of the error

**Screenshots**
<img width="1120" alt="Screen Shot 2022-07-27 at 4 44 17 PM" src="https://user-images.githubusercontent.com/39025103/181250523-9ad89187-e4b5-4523-83b1-3120a9c10f1b.png">

**Desktop (please complete the following information):**
 - Mac OS  12.3.1
 - Python 3.9.10

**Comment by AMR-KELEG** [comment]
Hi @uzairaj 

Have you tried fixing the `xcrun` error as per this answer? https://apple.stackexchange.com/a/209651/436838
