### ISSUE TITLE
[BUG] Installation problems on MacOS

### ISSUE THREAD

**Issue by Mastermouse44** [CAMeL-Lab/camel_tools#96]
I am receiving a legacy-install-failure when running `pip install camel-tools` from Terminal.

MacOS 12.5.1
Python 3.8.9

<img width="1863" alt="Screenshot 2022-08-19 at 16 52 35" src="https://user-images.githubusercontent.com/111590356/185666111-4e2e6e17-2357-48e5-99b3-8e23d334a17a.png">
<img width="1863" alt="Screenshot 2022-08-19 at 16 52 45" src="https://user-images.githubusercontent.com/111590356/185666127-701e316f-ee9d-4e20-871f-ca43a40ad9da.png">

**Comment by mosabalrsaheed** [comment]
Hi @Mastermouse44 , run this command python3 --version, you will probably find another python version hidden 3.10.*, 

downgrad through brew or pyv to any version 3.9 and you will be able to continue
