### ISSUE TITLE
[QUESTION] I can't Instanciate the  MLEDisambiguator Model 

### ISSUE THREAD

**Issue by MeryamAjlani** [CAMeL-Lab/camel_tools#97]
i did the steps indicated and installed CAMel Tools with pip isntall , however i couldn't instanciate the  MLEDisambiguator Model as it kept giving me this error:
 [Errno 2] No such file or directory: '/root/.camel_tools/data/morphology_db/calima-msa-r13/morphology.db'
Can you please tell me what i did the problem is ?

**Comment by LatifaA2** [comment]
I am facing the same issue

**Comment by LatifaA2** [comment]
you need to download the data.

**Comment by MeryamAjlani** [comment]
I ran the command as instructed :camel_data -i light yet it always gives me a invalid syntax [error], akthough i installed the tool as instructed.

**Comment by LatifaA2** [comment]
Yes, I faced the same problem with light. Try installing the default one it worked for me.

**Comment by LatifaA2** [comment]
! camel_data -i defaults

**Comment by MeryamAjlani** [comment]
thank you si much it worked !
